swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API For fetching transactions
      produces:
        - application/json
      responses:
        "200":
          description: All transactions retrieved successfully
          schema:
            $ref: "#/definitions/GetTransaction"
        "400":
          description: Invalid
        "401":
          description: Authentification error
        "500":
          description: Unauthorized
  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions by id API
      description: get transaction by id
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the transaction to return
      responses:
        "200":
          description: Get transaction by id successful
          schema:
            $ref: "#/definitions/GetTransactionById"
        "400":
          description: Invalid
        "401":
          description: Authentification error
        "500":
          description: Unauthorized
  /transaction/{id}/info:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions information by id  API
      description: post  transaction informations
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the transaction to post a note in
        - in: body
          name: Informations
          required: true
          schema:
            $ref: "#/definitions/Info"
      responses:
        "200":
          description: Note successfully created
          schema:
            $ref: "#/definitions/InfoSuccess"
        "400":
          description: Invalid
        "401":
          description: Authentification error
        "500":
          description: Unauthorized
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions information by id  API
      description: change  a transaction Info
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: The ID of the transaction to change a note
        - in: body
          name: Informations
          required: true
          schema:
            $ref: "#/definitions/Info"
      responses:
        "200":
          description: Note successfully changed
          schema:
            $ref: "#/definitions/InfoSuccess"
        "400":
          description: Invalid
        "401":
          description: Authentification error
        "500":
          description: Unauthorized

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  GetTransaction:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
        description:
          type: string
        amount:
          type: integer
  GetCategories:
    type: array
    items:
      type: object
      properties:
        category:
          type: string
  GetTransactionById:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: integer
      info:
        type: object
        properties:
          category:
            type: string
          note:
            type: string
  Info:
    type: object
    properties:
      note:
        type: string
      category:
        type: string
  InfoSuccess:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
